apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: project
spec:
  ingressClassName: nginx
  rules:
    - host: 34.45.200.6.nip.io
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 1234
            path: /
